services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: procureaccess-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassw0rd_h3r3
      #- MSSQL_PID=Developer
    #user: "0:0"
    ports:
      - 14333:1433
    volumes:
      - mssql_data:/var/opt/mssql
      # - mssql_data:/var/opt/mssql/data
      #- ./DB/init/01-create-db.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./DB/init:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dokploy-network

  api:
    build:
      context: .
      dockerfile: ./API/API.ProcureAccess/Dockerfile
    depends_on:
      - db
        #condition: service_healthy
    environment:
      #- ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      #- ConnectionStrings__ProcureAccess=Server=${DB_HOST};User Id=${DB_USER};Password=YourStrongPassw0rd_h3r3;TrustServerCertificate=True;
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: db
      DB_NAME: ProcureAccessDb
      DB_USER: sa
      MSSQL_SA_PASSWORD: YourStrongPassw0rd_h3r3
      #MSSQL_PID: Developer
    ports:
      - "8080"
    networks:
      - dokploy-network
    restart: on-failure

  client:
    build:
      context: ./CLIENT/CLIENT.ProcureAccess
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 4200:80
    # volumes:
    #   - ./:/app
        # - ./CLIENT/CLIENT.ProcureAccess:/app
        # - /app/node_modules
    # command: npm run start
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - WATCHPACK_POLLING=true
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  mssql_data:
