services:
  db:
    image: postgres:17-alpine
    container_name: procureaccess-db
    environment:
      POSTGRES_DB: ProcureAccessDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassw0rd_h3r3
    #environment: # ms sql server
      #- ACCEPT_EULA=Y
      #- MSSQL_SA_PASSWORD=YourStrongPassw0rd_h3r3
      #- MSSQL_PID=Developer
    #user: "0:0"
    ports:
      - "${DB_PORT_OUTER}:${DB_PORT_INNER}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # volumes:
    #   - mssql_data:/var/opt/mssql
      # - mssql_data:/var/opt/mssql/data
      #- ./DB/init/01-create-db.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./DB/init:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - procureaccess-net

  api:
    build:
      context: .
      dockerfile: ./API/API.ProcureAccess/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      #- ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      #- ConnectionStrings__ProcureAccess=Server=${DB_HOST};User Id=${DB_USER};Password=YourStrongPassw0rd_h3r3;TrustServerCertificate=True;
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ProcureAccessDb
      DB_USER: postgres
      DB_PASSWORD: YourStrongPassw0rd_h3r3
      #MSSQL_SA_PASSWORD: YourStrongPassw0rd_h3r3
      #MSSQL_PID: Developer
    ports:
      - "${API_PORT_OUTER}:${API_PORT_INNER}"
    # volumes:
    #   - ./API/API.ProcureAccess:/src
    networks:
      - procureaccess-net
    restart: on-failure

  client:
    build:
      context: ./CLIENT/CLIENT.ProcureAccess
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "${CLIENT_PORT_OUTER}:${CLIENT_PORT_INNER}"
    # volumes:
    #   - ./:/app
        # - ./CLIENT/CLIENT.ProcureAccess:/app
        # - /app/node_modules
    # command: npm run start
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - WATCHPACK_POLLING=true
    networks:
      - procureaccess-net

networks:
  procureaccess-net:
    driver: bridge

volumes:
  postgres_data:
